name: Build .NET Backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        working-directory: backend/MessageThreadAPI
        run: dotnet restore

      - name: Build backend
        working-directory: backend/MessageThreadAPI
        run: dotnet build --no-restore

      - name: Skip tests for now
        run: echo "Skipping tests - none implemented yet"