name: Build .NET Backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Print .NET SDK version
        run: dotnet --info

      - name: Restore dependencies
        working-directory: backend/MessageThreadAPI
        run: dotnet restore

      - name: Clean build
        run: dotnet clean backend/MessageThreadAPI/MessageThreadAPI.csproj

      - name: Build backend (verbose)
        run: dotnet build backend/MessageThreadAPI/MessageThreadAPI.csproj --no-restore --verbosity diag

      - name: Skip tests for now
        run: echo "Skipping tests - none implemented yet"